### ISSUE TITLE
Pip install fails due to issue with metadata generation

### ISSUE THREAD

**Issue by RoganGrant** [vibbits/nis2pyr#7]
Attempting to install within a virtual environment running python 3.9.11 with `pip install nis2pyr` leads to the following error:

```
Collecting nis2pyr
  Using cached nis2pyr-0.6.2-py3-none-any.whl (11 kB)
Collecting nd2==0.1.4
  Using cached nd2-0.1.4-cp39-cp39-macosx_11_0_arm64.whl (132 kB)
Collecting opencv-python==4.5.3.56
  Using cached opencv_python-4.5.3.56-cp39-cp39-macosx_11_0_arm64.whl (10.7 MB)
Collecting tifffile==2021.8.30
  Using cached tifffile-2021.8.30-py3-none-any.whl (171 kB)
Collecting ome-types==0.2.9
  Using cached ome_types-0.2.9-py3-none-any.whl (137 kB)
Collecting imagecodecs==2021.8.26
  Using cached imagecodecs-2021.8.26.tar.gz (10.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running egg_info
      creating /private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-pip-egg-info-u3dftrg8/imagecodecs.egg-info
      writing /private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-pip-egg-info-u3dftrg8/imagecodecs.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-pip-egg-info-u3dftrg8/imagecodecs.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-pip-egg-info-u3dftrg8/imagecodecs.egg-info/entry_points.txt
      writing requirements to /private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-pip-egg-info-u3dftrg8/imagecodecs.egg-info/requires.txt
      writing top-level names to /private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-pip-egg-info-u3dftrg8/imagecodecs.egg-info/top_level.txt
      writing manifest file '/private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-pip-egg-info-u3dftrg8/imagecodecs.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-install-h1tf5g4f/imagecodecs_20b8e6a946b64134bb551a3a87b00a95/setup.py", line 613, in <module>
          setup(
        File "/Users/rogangrant/Documents/GitHub/image_analysis/image_analysis_venv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Users/rogangrant/.pyenv/versions/3.9.11/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/rogangrant/.pyenv/versions/3.9.11/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/rogangrant/.pyenv/versions/3.9.11/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/rogangrant/Documents/GitHub/image_analysis/image_analysis_venv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/Users/rogangrant/Documents/GitHub/image_analysis/image_analysis_venv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/Users/rogangrant/Documents/GitHub/image_analysis/image_analysis_venv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/Users/rogangrant/Documents/GitHub/image_analysis/image_analysis_venv/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/Users/rogangrant/.pyenv/versions/3.9.11/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
          self._add_defaults_ext()
        File "/Users/rogangrant/.pyenv/versions/3.9.11/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/Users/rogangrant/.pyenv/versions/3.9.11/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/Users/rogangrant/.pyenv/versions/3.9.11/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/private/var/folders/3m/ms22yqxx2dq38gxl025800nh0000gn/T/pip-install-h1tf5g4f/imagecodecs_20b8e6a946b64134bb551a3a87b00a95/setup.py", line 582, in finalize_options
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

This error persists if I specify commit fae5229910d97a23f360f323953541c83c80f4b6. If you have any insight, I would very much appreciate it. Thank you for your help!

**Comment by RoganGrant** [comment]
Note that installing numpy separately does partially fix, but the standard install does not work
